spring:
  application:
    name: alumnos

  datasource:
    url: jdbc:mysql://localhost:3306/alumnos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Servidor1-
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true